export const knowledgePoints = [
  {
    id: 'architecture-foundation',
    priority: 'P0',
    module: '系统架构设计',
    title: '软件架构基础与架构风格',
    summary: '掌握构件、连接件、约束、4+1 视图、分层、管道过滤器、仓库、事件驱动、MVC、微内核、C/S、B/S 等。',
    resources: ['基础录播课/第十五章-系统架构设计', '架构直播4：架构设计+质量属性+架构评估.pdf', '架构设计师课程“4+1”视图.pdf'],
    question: '软件架构风格常见类型有哪些？各适合什么场景？',
    answer: '分层适合职责清晰系统；管道过滤器适合批处理；仓库适合共享数据；事件驱动适合松耦合异步；MVC 适合交互式 Web；微内核适合插件化扩展。',
  },
  {
    id: 'quality-attributes',
    priority: 'P0',
    module: '质量属性',
    title: '质量属性与场景化表达',
    summary: '重点掌握性能、可用性、安全性、可修改性、易用性、可测试性、可靠性，以及刺激源、刺激、环境、制品、响应、响应度量。',
    resources: ['基础录播课/第十六章-系统质量属性和架构评估/质量属性.pdf', '架构直播4：架构设计+质量属性+架构评估.pdf'],
    question: '如何用场景化语言描述一个可用性需求？',
    answer: '示例：当主服务器在正常运行环境下发生故障时，系统应在 1 分钟内自动切换到备用服务器，并保证核心业务不中断。',
  },
  {
    id: 'architecture-evaluation',
    priority: 'P0',
    module: '架构评估',
    title: 'SAAM、ATAM、敏感点与权衡点',
    summary: '案例高频。会解释风险点、非风险点、敏感点、权衡点、效用树和质量属性折中。',
    resources: ['基础录播课/第十六章-系统质量属性和架构评估/架构评估.pdf', '2024年系统架构设计师核心考点提炼.pdf'],
    question: '敏感点和权衡点的区别是什么？',
    answer: '敏感点影响一个或多个构件特性并影响某个质量属性；权衡点同时影响多个质量属性，是多个质量属性的敏感点。',
  },
  {
    id: 'absd-dssa-cbse',
    priority: 'P0',
    module: '系统架构设计',
    title: 'ABSD、DSSA、CBSE 与软件复用',
    summary: '掌握基于架构的软件开发、特定领域软件架构、构件化开发、构件特征与组装方式。',
    resources: ['基础录播课/第十五章-系统架构设计/软件复用、ABSD和DSSA.pdf', '2024年系统架构设计师核心考点提炼.pdf'],
    question: 'ABSD 的三个基础是什么？',
    answer: '功能分解、通过选择架构风格实现质量和业务需求、软件模板使用。',
  },
  {
    id: 'case-analysis',
    priority: 'P0',
    module: '案例分析',
    title: '案例分析答题框架',
    summary: '按质量属性、架构风格、数据库、安全、高并发、云原生、大数据等题型形成答题模板。',
    resources: ['《系统架构设计师案例题备考攻略》.pdf', '第二十二章-传统架构案例分析专题', '第二十三章-架构案例分析专题'],
    question: '案例题问“如何提升性能”时，常用答题点有哪些？',
    answer: '缓存、异步削峰、负载均衡、CDN、数据库索引/读写分离/分库分表、服务拆分、限流降级、资源调度。',
  },
  {
    id: 'paper-writing',
    priority: 'P0',
    module: '论文',
    title: '论文模板与四大主题',
    summary: '准备云原生/服务网格、高并发性能优化、大数据/Kappa、安全与可靠性四类模板。',
    resources: ['架构直播9：论文-下(更新).pdf', '2026年上半年架构论文预测.pdf', '架构论文/'],
    question: '架构论文的稳定结构是什么？',
    answer: '摘要、项目背景、目标与难点、架构设计方案、关键技术应用、效果评价与总结。',
  },
  {
    id: 'software-engineering',
    priority: 'P1',
    module: '软件工程',
    title: '软件工程、需求与生命周期模型',
    summary: '瀑布、原型、增量、螺旋、敏捷、UP/RUP、需求分类、需求获取、需求变更、测试、维护、再工程。',
    resources: ['基础录播课/第十一章-软件工程', '第十二章-软件工程扩展', '架构直播3：软件工程+面向对象精华提炼(更新).pdf'],
    question: '螺旋模型的典型特点是什么？',
    answer: '引入风险分析，循环包括制定计划、风险分析、实施工程、客户评估。',
  },
  {
    id: 'object-oriented-uml',
    priority: 'P1',
    module: '面向对象',
    title: 'UML、面向对象原则与设计模式',
    summary: 'UML 图分类、用例图、类图、顺序图、状态图、活动图、构件图、部署图、SOLID、常用设计模式。',
    resources: ['基础录播课/第十三章-面向对象设计', '面向对象.pptx'],
    question: '面向对象设计原则有哪些？',
    answer: '单一职责、开闭、里氏替换、依赖倒置、接口隔离、组合复用、迪米特法则。',
  },
  {
    id: 'database-design',
    priority: 'P1',
    module: '数据库',
    title: '数据库设计、范式、并发与 NoSQL',
    summary: '三级模式两级映像、E-R、关系代数、函数依赖、范式、反规范化、封锁协议、备份恢复、NoSQL、主从复制。',
    resources: ['基础录播课/第九章-数据库设计', '架构直播2 数据库精讲-更新.pdf'],
    question: '三级模式两级映像解决什么问题？',
    answer: '外模式、模式、内模式通过两级映像保证逻辑独立性和物理独立性。',
  },
  {
    id: 'web-high-concurrency',
    priority: 'P1',
    module: 'Web 与高并发',
    title: '缓存、负载均衡、Redis 与高并发设计',
    summary: 'MVC、REST、缓存、Redis、Memcached、CDN、集群、读写分离、分库分表、静态化、有状态/无状态。',
    resources: ['Redis常见场景详解.pdf', 'Redis的基础理论知识.pdf', '论高并发系统性能优化技术及其应用.pdf'],
    question: '负载均衡常见算法有哪些？',
    answer: '轮询、加权轮询、源地址哈希、目标地址哈希、随机、最小连接数、加权最小连接数、加权百分比。',
  },
  {
    id: 'reliability-performance',
    priority: 'P1',
    module: '可靠性与性能',
    title: '可靠性指标与性能评价',
    summary: 'MTTF、MTTR、MTBF、可用性公式、恢复块、N 版本程序设计、主动/被动冗余、吞吐量、响应时间。',
    resources: ['第十七章-软件可靠性/软件可靠性.pdf', '第七章-系统配置与性能评价/6-系统配置与性能评价.pdf'],
    question: '可用性公式是什么？',
    answer: '可用性 = MTTF / (MTTF + MTTR) * 100%，MTBF = MTTF + MTTR。',
  },
  {
    id: 'security',
    priority: 'P1',
    module: '信息安全',
    title: '信息安全与安全架构',
    summary: 'CIA、摘要、对称/非对称加密、数字签名、访问控制、SQL 注入、主动/被动攻击、WPDRRC。',
    resources: ['基础录播课/第十章-信息安全技术', '第二十三章-架构案例分析专题/32、安全架构.pdf'],
    question: 'WPDRRC 模型包括哪些环节？',
    answer: '预警、保护、检测、响应、恢复、反击；三要素为人员、策略、技术。',
  },
  {
    id: 'operating-system',
    priority: 'P2',
    module: '操作系统',
    title: '进程、死锁、存储与文件',
    summary: '进程线程、同步互斥、PV、前趋图、资源图、死锁、页式存储、快表、文件结构。',
    resources: ['基础录播课/第三章-操作系统基础', '架构直播1：操作系统精讲.pdf'],
    question: '死锁产生的必要条件是什么？',
    answer: '互斥、占有并等待、不可剥夺、循环等待。',
  },
  {
    id: 'network',
    priority: 'P2',
    module: '计算机网络',
    title: '网络协议、IP 与网络规划',
    summary: 'OSI/RM、TCP/IP、IP 地址、子网、DNS、HTTP、FTP、SMTP、DHCP、SNMP、网络规划、5G、虚拟化。',
    resources: ['基础录播课/第四章-计算机网络基础'],
    question: '常见应用层协议端口有哪些？',
    answer: 'HTTP 80、FTP 20/21、SMTP 25、DNS 53、DHCP 67、SNMP 161。',
  },
  {
    id: 'computer-organization',
    priority: 'P2',
    module: '计算机组成',
    title: 'CPU、Cache、流水线、总线与校验码',
    summary: 'CPU、Cache 地址映像与替换、流水线、总线、磁盘、校验码、CISC/RISC、Flynn 分类。',
    resources: ['基础录播课/第二章-计算机基础（选学）'],
    question: '串行总线和并行总线的典型差异是什么？',
    answer: '串行逐位传输、适合较长距离；并行多位同时传输、适合短距离。',
  },
  {
    id: 'embedded',
    priority: 'P2',
    module: '嵌入式',
    title: '嵌入式系统与处理器分类',
    summary: 'MCU、EMPU、DSP、SOC、嵌入式操作系统、多核处理器、嵌入式架构案例。',
    resources: ['基础录播课/第六章-嵌入式技术应用'],
    question: '常见嵌入式处理器分类有哪些？',
    answer: '嵌入式微控制器 MCU、嵌入式微处理器 EMPU、嵌入式 DSP、片上系统 SOC。',
  },
  {
    id: 'project-ip-math-english',
    priority: 'P2',
    module: '送分模块',
    title: '项目管理、知识产权、数学与英语',
    summary: '进度、配置、质量、风险、著作权、专利、标准化、概率、图论、线性规划、网络计划、专业英语。',
    resources: ['第十四章-项目管理', '第二十一章-知识产权与标准化', '第二十章-数学与经济管理知识补充', '系统架构设计师-英文词汇自测表 .pdf'],
    question: '知识产权题的复习重点是什么？',
    answer: '著作权/专利权保护对象、保护期限、权利归属、侵权判断、标准分类和生命周期。',
  },
  {
    id: 'cloud-native',
    priority: 'P3',
    module: '热点技术',
    title: '云原生、服务网格与微服务治理',
    summary: '容器、Kubernetes、服务网格、DevOps、弹性伸缩、注册发现、熔断、限流、降级。',
    resources: ['31.1-云原生架构.pdf', '论云原生服务网格架构设计及其应用.pdf', '2026年上半年架构论文预测.pdf'],
    question: '微服务面临的典型挑战有哪些？',
    answer: '服务治理、分布式事务、链路追踪、配置管理、部署复杂度、监控告警、数据一致性。',
  },
  {
    id: 'big-data-ai',
    priority: 'P3',
    module: '热点技术',
    title: '大数据、AI Agent 与未来信息技术',
    summary: 'Hadoop、HDFS、MapReduce、Hive、Spark、Lambda/Kappa、AI、大模型、Agent、边缘计算、数字孪生、区块链。',
    resources: ['Hadoop生态核心组件介绍.pdf', 'Agent详解.pdf', '第十九章-未来信息综合技术', '论基于Kappa架构的实时数据处理系统设计及其应用.pdf'],
    question: 'Kappa 架构适合什么场景？',
    answer: '适合以流处理为核心、希望用一套实时处理链路同时承担实时和历史重算的数据处理系统。',
  },
];

export const studyPlan = [
  { id: 'week-01', week: 1, title: '考试大纲、导学课、核心考点目录、2024 真题摸底', phase: '框架建立', focus: '建立知识地图，生成第一批卡片和薄弱点清单。' },
  { id: 'week-02', week: 2, title: '核心考点提炼 1-30：软件工程、信息系统、需求', phase: '框架建立', focus: '把高频名词做成概念卡和对比卡。' },
  { id: 'week-03', week: 3, title: '操作系统、计算机组成', phase: '上午基础', focus: '进程、死锁、存储、CPU、Cache、流水线。' },
  { id: 'week-04', week: 4, title: '数据库设计专项', phase: '上午基础', focus: '范式、关系代数、封锁协议、备份恢复、NoSQL。' },
  { id: 'week-05', week: 5, title: '软件工程、需求工程、测试与维护', phase: '上午基础', focus: '生命周期模型、UP/RUP、敏捷、需求变更、测试。' },
  { id: 'week-06', week: 6, title: '面向对象、UML、设计模式、项目管理', phase: '上午基础', focus: 'UML 图、设计原则、模式、项目管理送分点。' },
  { id: 'week-07', week: 7, title: '架构基础、构件、4+1 视图、架构风格', phase: '核心架构', focus: 'P0 核心，开始做案例表达。' },
  { id: 'week-08', week: 8, title: 'ABSD、DSSA、CBSE、软件复用', phase: '核心架构', focus: '背定义，练习“方法步骤+适用场景”。' },
  { id: 'week-09', week: 9, title: '质量属性、可靠性、性能', phase: '核心架构', focus: '所有质量属性都写成场景化表达。' },
  { id: 'week-10', week: 10, title: '架构评估、ATAM、敏感点、权衡点', phase: '核心架构', focus: '形成案例题标准答题框架。' },
  { id: 'week-11', week: 11, title: '传统案例：软件工程、数据库、Web 应用', phase: '案例专项', focus: '每天 1 道案例小题。' },
  { id: 'week-12', week: 12, title: '架构案例：信息系统、层次架构、架构风格', phase: '案例专项', focus: '按题干识别架构风格与质量属性。' },
  { id: 'week-13', week: 13, title: '云原生、SOA、微服务、安全架构', phase: '案例专项', focus: '补充热点技术和安全答题素材。' },
  { id: 'week-14', week: 14, title: '大数据、Hadoop、Redis、高并发', phase: '案例专项', focus: '高并发和大数据可同时服务论文。' },
  { id: 'week-15', week: 15, title: '论文模板：云原生/服务网格', phase: '论文专项', focus: '完成第一篇可背诵模板。' },
  { id: 'week-16', week: 16, title: '论文模板：高并发性能优化', phase: '论文专项', focus: '结合工作项目改写成自己的经历。' },
  { id: 'week-17', week: 17, title: '论文模板：大数据/Kappa、安全可靠', phase: '论文专项', focus: '完成 4 篇模板和素材库。' },
  { id: 'week-18', week: 18, title: '2024、2025 真题优先做', phase: '真题冲刺', focus: '按错题反查知识点。' },
  { id: 'week-19', week: 19, title: '2018-2023 真题轮刷与案例复盘', phase: '真题冲刺', focus: '限时练习，整理固定答题模板。' },
  { id: 'week-20', week: 20, title: '模拟机考、论文背诵、考前必背清单', phase: '真题冲刺', focus: '只复习 P0/P1、错题、论文模板。' },
];

export const paperTemplates = [
  {
    id: 'paper-cloud-native',
    title: '云原生/服务网格架构设计',
    useFor: '云原生、微服务治理、服务网格、可观测性、弹性伸缩。',
    structure: ['项目背景', '业务挑战', '总体架构', '服务治理与安全', '效果评价'],
  },
  {
    id: 'paper-high-concurrency',
    title: '高并发系统性能优化',
    useFor: '秒杀、交易、支付、预约、内容平台、流量突增系统。',
    structure: ['性能目标', '缓存与异步', '负载均衡', '数据库优化', '限流降级与监控'],
  },
  {
    id: 'paper-kappa',
    title: 'Kappa 架构实时数据处理',
    useFor: '日志分析、风控、推荐、实时指标、数据中台。',
    structure: ['数据采集', '流处理', '存储设计', '一致性与容错', '业务效果'],
  },
  {
    id: 'paper-security-reliability',
    title: '安全与可靠性架构设计',
    useFor: '政企系统、金融系统、核心业务系统、7x24 小时系统。',
    structure: ['安全目标', '访问控制', '加密审计', '冗余容灾', '可靠性评估'],
  },
];
